// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFOvmzFX7A-tNJaLaSDzsHZdAjfS4fMWc',
    appId: '1:231510617643:web:9213852500d5fa64a0c46e',
    messagingSenderId: '231510617643',
    projectId: 'reegs-81fd4',
    authDomain: 'reegs-81fd4.firebaseapp.com',
    storageBucket: 'reegs-81fd4.appspot.com',
    measurementId: 'G-M1PGXWYGT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0vY4HARfTKHUDhtppC2NZtRDcrf5lxcA',
    appId: '1:231510617643:android:08c45dda7aef935fa0c46e',
    messagingSenderId: '231510617643',
    projectId: 'reegs-81fd4',
    storageBucket: 'reegs-81fd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-MNF9cZTERJ1XODqQ0ppbtyFyMwQ1aMo',
    appId: '1:231510617643:ios:9473e8ca58234e50a0c46e',
    messagingSenderId: '231510617643',
    projectId: 'reegs-81fd4',
    storageBucket: 'reegs-81fd4.appspot.com',
    iosClientId: '231510617643-9hc7n0m7uvdm22f95l2gl1maahrdad6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.reegs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-MNF9cZTERJ1XODqQ0ppbtyFyMwQ1aMo',
    appId: '1:231510617643:ios:9473e8ca58234e50a0c46e',
    messagingSenderId: '231510617643',
    projectId: 'reegs-81fd4',
    storageBucket: 'reegs-81fd4.appspot.com',
    iosClientId: '231510617643-9hc7n0m7uvdm22f95l2gl1maahrdad6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.reegs',
  );
}
