// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgLjHDAP4_G4ixmObokaaLE9GFhA7OwwI',
    appId: '1:70825632359:web:184666238c321219d5eac2',
    messagingSenderId: '70825632359',
    projectId: 'egoproject-cce67',
    authDomain: 'egoproject-cce67.firebaseapp.com',
    storageBucket: 'egoproject-cce67.appspot.com',
    measurementId: 'G-4D8ZW7HSF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALeWum41WyRfuxmgs8z3m7kVzRW-kMGVk',
    appId: '1:70825632359:android:4ce3a35fafd292afd5eac2',
    messagingSenderId: '70825632359',
    projectId: 'egoproject-cce67',
    storageBucket: 'egoproject-cce67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt7Tn9SmEue3i3ftN0tmQPK6XEuzwS0_s',
    appId: '1:70825632359:ios:827b9b5013fcc435d5eac2',
    messagingSenderId: '70825632359',
    projectId: 'egoproject-cce67',
    storageBucket: 'egoproject-cce67.appspot.com',
    iosBundleId: 'com.example.reegs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt7Tn9SmEue3i3ftN0tmQPK6XEuzwS0_s',
    appId: '1:70825632359:ios:827b9b5013fcc435d5eac2',
    messagingSenderId: '70825632359',
    projectId: 'egoproject-cce67',
    storageBucket: 'egoproject-cce67.appspot.com',
    iosBundleId: 'com.example.reegs',
  );
}
