import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:reegs/models/register/acquired_model.dart';

final EIProvider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final NSProvider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final FTProvider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final JPProvider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final HSPProvider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final PsyProvider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final SocProvider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

//Noの場合はここに入れる
final En0Provider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final En1Provider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final En2Provider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final En3Provider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final En4Provider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final En5Provider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final En6Provider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final En7Provider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final En8Provider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final En9Provider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final iwayuruProvider =
    StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

enum Question {
  q1,
  q2,
  q3,
  q4,
  q5,
  q6,
  q7,
  q8,
  q9,
  q10,
  q11,
  q12,
  q13,
  q14,
  q15,
  q16,
  q17,
  q18,
  q19,
  q20,
  q21,
  q22,
  q23,
  q24,
  q25,
  q26,
  q27,
  q28,
  q29,
  q30,
  q31,
  q32,
  q33,
  q34,
  q35,
  q36,
  q37,
  q38,
  q39,
  q40,
  q41,
  q42,
  q43,
  q44,
  q45,
  q46,
  q47,
  q48,
  q49,
  q50,
  q51,
  q52,
  q53,
  q54,
  q55,
  q56,
  q57,
  q58,
  q59,
  q60,
  q61,
  q62,
  q63,
  q64,
  q65,
  q66,
  q67,
  q68,
  q69,
  q70,
  q71,
  q72,
  q73,
  q74,
  q75,
  q76,
  q77,
  q78,
  q79,
  q80,
  q81,
  q82,
  q83,
  q84,
  q85,
  q86,
  q87,
  q88,
  q89,
  q90,
  q91,
  q92,
  q93,
  q94,
  q95,
  q96,
  q97,
  q98,
  q99,
  q100,
  q101,
  q102,
  q103,
  q104,
  q105,
  q106,
  q107,
  q108,
  q109,
  q110,
  q111,
  q112,
  q113,
  q114,
  q115,
  q116,
  q117,
  q118,
  q119,
  q120,
  q121,
  q122,
  q123,
  q124,
  q125,
  q126,
  q127,
  q128,
  q129,
  q130,
  q131,
  q132,
  q133,
  q134,
  q135,
  q136,
  q137,
  q138,
  q139,
  q140
}

const Map<Question, String> questionTexts = {
  Question.q1: 'あなたは占いや心理テストを信じますか',
  Question.q2: 'プライベートなことを\n質問されるのが好きだ',
  Question.q3: '衝動に駆られて行動を起こすことが多い',
  Question.q4: '口論になった際\n相手を説き伏せられる自信がある',
  Question.q5: '大切な人が明らかに苦しそうな時\nあなたが真っ先に言いそうなのは…',
  Question.q6: '人とすぐに打ち解けることができると思う',
  Question.q7: 'どちらかというと他人の良いところより\n欠点や短所などが目に付く',
  Question.q8: '失敗した時\nまず自分以外に原因を探してしまう',
  Question.q9: '食事や飲み会は、同伴者が',
  Question.q10: '他人は自分ほど、\n人生を深く味わっていないと思う',
  Question.q11: '他人から助けや同情を受けることは嫌いだ',
  Question.q12: '目的を定めて貯金をし\nそれを実現した経験がある',
  Question.q13: '信頼関係がある人を除いて\n人を馬鹿にしてしまう事がある',
  Question.q14: 'あなたは面接官です。\nあなたがまず気になるのは…',
  Question.q15: '駅や街にいる全く知らない人について、\n特に感想を抱かない',
  Question.q16: '未来に何が起こるかより、\n今起きていることが大事だ',
  Question.q17: '他人の中に、自分にないものを見つけると\n羨ましく思う',
  Question.q18: '必要があれば人と対立することを恐れない',
  Question.q19: '問題が起きても、\n自分一人で考えて解決しようとする方だ',
  Question.q20: '自分の魅力を\n周りの人に分かって欲しいと思っている',
  Question.q21: '「意外と毒舌だよね」などと\n言われたことがある',
  Question.q22: '他人を良い気分にさせる方法を\nすぐに思いつく',
  Question.q23: '他の人から見て、\nあなたは落ち着いていると思う',
  Question.q24: '人類の進歩により必要なのは',
  Question.q25: '小さいころよくやっていたのは…',
  Question.q26: '自分の将来の仕事や生き方について\nあまり興味がない',
  Question.q27: '自分がいまこうしていられるのは、\n基本的に自分のおかげである',
  Question.q28: '困っている人を見ると\n手を差し伸べずにはいられない',
  Question.q29: '人が見ていない時に\n「ちょっと悪い事をしてしまおう」と\n魔が差すことがある',
  Question.q30: '時間にルーズな人間に\n腹を立てることがある',
  Question.q31: '環境の微妙な変化によく気づきやすい',
  Question.q32: '同時にたくさんのことを頼まれても、\nつい引き受けてしまう',
  Question.q33: '他人の行動や周囲の状況を\n一歩引いて見ることが多いと思う',
  Question.q34: '自分が欲しいものがあると、\n我慢できないでよくすぐに買ってしまう',
  Question.q35: 'チームとして正しい結論を出すためには、\n揉め事は避けて通れない',
  Question.q36: 'いつか自分が罪を犯すような気がする',
  Question.q37: 'あなたにとって、比較的重要性が高いのは…',
  Question.q38: '怒った時、あなたの言葉や行動は\n乱暴になることが多い',
  Question.q39: '打ち合わせ中に誰かが泣き出しました。\nまずあなたは…',
  Question.q40: 'SNSなどで日常を公開することに抵抗がない',
  Question.q41: '誰にも言えない様な秘密がある',
  Question.q42: '他人との感情のつながりは\nとても大切だと思う',
  Question.q43: '自分は優れていて特別な人だと思う',
  Question.q44: '不満なことは、\nはっきり伝えるほうだ',
  Question.q45: '他人と長く時間を過ごすことに\n疲労を感じやすい',
  Question.q46: 'チームの意見が割れました。\nリーダーのあなたはまず…',
  Question.q47: '会話の中で自分の自慢をすることがよくある',
  Question.q48: 'あなたは他の人よりも\n上に立つことや有名になることに興味がある',
  Question.q49: 'あなたは一般的なルールや習慣を\nすぐに受け入れる方だ',
  Question.q50: '仲間はずれにされたり無視されたりするのは\nとても怖いと感じる',
  Question.q51: '一人でいる時間が十分に欲しいと思う',
  Question.q52: '面白そうだと思うのは…',
  Question.q53: '自分の利害に基づいて人を動かしたいと思う',
  Question.q54: '何もしないで\nリラックスしている時間が好きだ',
  Question.q55: '自分は人生で成功すると確信している',
  Question.q56: '色々な気持ちが一度に押し寄せて\n辛くなることがある',
  Question.q57: 'プレゼントをあげるのが好きで、\n人が喜ぶ顔を見るのを嬉しく思う',
  Question.q58: '楽しさより、正しさで行動を決める',
  Question.q59: 'チャットやメールなど、\n自分からやり取りをはじめる方だ',
  Question.q60: '自分は能力があり、\n社会に貢献できると信じている',
  Question.q61: 'あなたは海賊船の船長です。\n誘いたい船員は…',
  Question.q62: '人から良い反応を得るためには、\n第一印象がとても大切だ',
  Question.q63: '他の人から見て、\nあなたはのんびりしていると思う',
  Question.q64: '人に頼られすぎると\n負担に感じることがある',
  Question.q65: '誰もいない場所へ\n突然行きたくなることがある',
  Question.q66: '所持金や鑑賞した作品など、\n生活の記録を取る方だ',
  Question.q67: '初対面で愛想が悪いのも\n個性のひとつだと思う',
  Question.q68: '辛い状況が続くと、\n誰もいない場所に閉じこもりたくなる',
  Question.q69: '監視されていると\n本来の能力がほとんど発揮できない',
  Question.q70: '占いや手相などが当たっていて\n驚いたことがある',
  Question.q71: '暗号やパズルなどに\n挑戦することに苦痛を感じない',
  Question.q72: '同時に異なるタスクを強いられると、\nパニックに陥る',
  Question.q73: '死んだらどうなるかなど、\n考えるだけ無駄である',
  Question.q74: '気分が一定であることを重要視している',
  Question.q75: '自分には正直でいたいと感じる',
  Question.q76: '締切を提示されたら、あなたはまず…',
  Question.q77: '自分がやりたいことを我慢するのは嫌だ',
  Question.q78: 'ほしいものを手に入れるためには、\nどんな方法でも使う',
  Question.q79: '自分の周りの友人同士を\n引き合わせることがある',
  Question.q80: 'ルールに忠実な人は\n場合によって損をしていると思う',
  Question.q81: 'どうしてもタトゥーを入れるなら',
  Question.q82: '自分を平凡な人だとは思いたくない',
  Question.q83: '予想外の出来事が起きるとあなたは…',
  Question.q84: '素晴らしいアイデアは',
  Question.q85: 'たいていの人に理解してもらえない\n自分なりの意見を持っている',
  Question.q86: '一度決めたら最後までしっかりとやりとげる',
  Question.q87: '他人から少し冷たいとか、\n近づきにくいと言われたことがある',
  Question.q88: '一目で理解しにくいアイデアには\n関心を抱きにくい',
  Question.q89: '演奏や創作、ダンスなどの\n自己表現は自分に向いていない',
  Question.q90: '他人に何かを強制する、\nまたは他人から強制されると\n反抗的になることが多い',
  Question.q91: 'よく嘘をつく',
  Question.q92: '即座に気の利いた切り返しをするのが\n得意ではない',
  Question.q93: '約束事をすぐに破ってしまいやすい',
  Question.q94: '寝ることで悩みはいくらかマシになる',
  Question.q95: '自分でできることであれば、\n他人に頼れる場合でも自分でこなす',
  Question.q96: '口が達者だと言われることが多い',
  Question.q97: '恋人が言った\n冗談の意味が分かりませんでした\nあなたはまず…',
  Question.q98: '目の前で誰かが泣いてても\n心が全く動かない',
  Question.q99: '結果を出しているものには\n逆らえないと思う',
  Question.q100: '多少完成度が低くても、\n締切は厳守したいと思う',
  Question.q101: '他人が自分のことを\nどう思うのかがとても気になる',
  Question.q102: '正論を言って場をシラけさせた経験がある',
  Question.q103: '新しい環境や出会いに抵抗がある',
  Question.q104: '新しい考えや初めてのことについては、\n不安を感じやすく慎重になる',
  Question.q105: '自分は何も悪いことをしていないのに、\n他の人からよく責められる',
  Question.q106: '100歳まで長生きする方法があるなら、\n苦しんででも実践したい',
  Question.q107: '起こってもいないことを心配することや\n取り越し苦労をすることがよくある',
  Question.q108: '頭の中で色々な楽しい計画を\n立てることがよくある',
  Question.q109: '何かしらの失敗をしないよう\n常に気を張っている気がする',
  Question.q110: '環境音や話し声に反応してしまいやすい',
  Question.q111: '「似顔絵描いて」と頼まれました。\nあなたが答えそうなのは…',
  Question.q112: '鍵や財布など\n置く（しまう）場所が定まっている',
  Question.q113: '友人や恋人、家族に\n自分から電話をかけるほうだ',
  Question.q114: 'クラスや職場などの人間関係を\n把握していない',
  Question.q115: '意識していないが、\n演技していると言われることがある',
  Question.q116: '人の目を見るのが苦手だ',
  Question.q117: 'あなたの関心が向きやすいのは…',
  Question.q118: '上司や先輩から\n「可愛がられる」ようなことがあまりない',
  Question.q119: '注目されるのが好きで、\n人前に出るのが好きだ',
  Question.q120: '悩みが多いのは…',
  Question.q121: 'ルーティンワークをこなしていくことが\nどちらかといえば得意だ',
  Question.q122: '長年温めていた計画を多くの人に発表します。\nあなたはまず…',
  Question.q123: '物事について\n深く考えすぎることはあまりない',
  Question.q124: '問題が起きると\n誰かに相談して意見を仰ぐ方だ',
  Question.q125: '人を傷つけるような描写や表現が苦手だ',
  Question.q126: '公平で公正に行われているかを\nとても気にする',
  Question.q127: 'なんとなくでも人生の設計があり、\nそれに沿って進む気がある',
  Question.q128: '多くの人から好かれていると感じる',
  Question.q129: '冗談を言ったり、楽しい話をして\n人を楽しませるのが好きだ',
  Question.q130: '夜ごはんを作ることになりました。\nあなたはまず…',
  Question.q131: '何も考えず、\nぼーっと景色や人々を眺めていられる',
  Question.q132: '他人の気分に影響を受けやすい',
  Question.q133: '初対面の人と話す話題はすぐ思いつく方だ',
  Question.q134: 'テレビやYoutubeを見ていて、\n退屈なCMや番組構成に文句を言ってしまうことがある',
  Question.q135: '空想の中で、\nドラマの主役を演じることがある',
  Question.q136: '今まで人のことを、\n心の底から好きになったという経験がない',
  Question.q137: '駅前で裸の政治家が演説をしていました。\nあなたがまず気になるのは…',
  Question.q138: 'あなたは他人から見て、\n悩みが少なく幸せな人に見えると思う',
  Question.q139: '他人の悪事を見過ごすのが苦手だ',
  Question.q140: '運命や宿命を信じますか',
};

const Map<Question, List<String>> questionAnswers = {
  Question.q1: ['はい', 'いいえ'],
  Question.q2: ['はい', 'いいえ'],
  Question.q3: ['はい', 'いいえ'],
  Question.q4: ['はい', 'いいえ'],
  Question.q5: ['「どうしたの？」', '「大丈夫？」'],
  Question.q6: ['はい', 'いいえ'],
  Question.q7: ['はい', 'いいえ'],
  Question.q8: ['はい', 'いいえ'],
  Question.q9: ['多いほどいい', '少ないほどいい'],
  Question.q10: ['はい', 'いいえ'],
  Question.q11: ['はい', 'いいえ'],
  Question.q12: ['はい', 'いいえ'],
  Question.q13: ['はい', 'いいえ'],
  Question.q14: ['経歴', '話し方・態度'],
  Question.q15: ['はい', 'いいえ'],
  Question.q16: ['はい', 'いいえ'],
  Question.q17: ['はい', 'いいえ'],
  Question.q18: ['はい', 'いいえ'],
  Question.q19: ['はい', 'いいえ'],
  Question.q20: ['はい', 'いいえ'],
  Question.q21: ['はい', 'いいえ'],
  Question.q22: ['はい', 'いいえ'],
  Question.q23: ['はい', 'いいえ'],
  Question.q24: ['論文', '物語'],
  Question.q25: ['みんなでボール遊び', 'ひとりでゲーム'],
  Question.q26: ['はい', 'いいえ'],
  Question.q27: ['はい', 'いいえ'],
  Question.q28: ['はい', 'いいえ'],
  Question.q29: ['はい', 'いいえ'],
  Question.q30: ['はい', 'いいえ'],
  Question.q31: ['はい', 'いいえ'],
  Question.q32: ['はい', 'いいえ'],
  Question.q33: ['はい', 'いいえ'],
  Question.q34: ['はい', 'いいえ'],
  Question.q35: ['はい', 'いいえ'],
  Question.q36: ['はい', 'いいえ'],
  Question.q37: ['話し合いの時間', '話し合いの場所'],
  Question.q38: ['はい', 'いいえ'],
  Question.q39: ['迷惑に感じる', '心配に思う'],
  Question.q40: ['はい', 'いいえ'],
  Question.q41: ['はい', 'いいえ'],
  Question.q42: ['はい', 'いいえ'],
  Question.q43: ['はい', 'いいえ'],
  Question.q44: ['はい', 'いいえ'],
  Question.q45: ['はい', 'いいえ'],
  Question.q46: ['統計を取り総意を出す', '1人ずつに話を聞いてみる'],
  Question.q47: ['はい', 'いいえ'],
  Question.q48: ['はい', 'いいえ'],
  Question.q49: ['はい', 'いいえ'],
  Question.q50: ['はい', 'いいえ'],
  Question.q51: ['はい', 'いいえ'],
  Question.q52: ['著名な玄人の安定した漫才', '無名な若手の支離滅裂な一発芸'],
  Question.q53: ['はい', 'いいえ'],
  Question.q54: ['はい', 'いいえ'],
  Question.q55: ['はい', 'いいえ'],
  Question.q56: ['はい', 'いいえ'],
  Question.q57: ['はい', 'いいえ'],
  Question.q58: ['はい', 'いいえ'],
  Question.q59: ['はい', 'いいえ'],
  Question.q60: ['はい', 'いいえ'],
  Question.q61: ['目星を付けて誘う', '道中で見つけてゆく'],
  Question.q62: ['はい', 'いいえ'],
  Question.q63: ['はい', 'いいえ'],
  Question.q64: ['はい', 'いいえ'],
  Question.q65: ['はい', 'いいえ'],
  Question.q66: ['はい', 'いいえ'],
  Question.q67: ['はい', 'いいえ'],
  Question.q68: ['はい', 'いいえ'],
  Question.q69: ['はい', 'いいえ'],
  Question.q70: ['はい', 'いいえ'],
  Question.q71: ['はい', 'いいえ'],
  Question.q72: ['はい', 'いいえ'],
  Question.q73: ['はい', 'いいえ'],
  Question.q74: ['はい', 'いいえ'],
  Question.q75: ['はい', 'いいえ'],
  Question.q76: ['予定を立ててみる', '伸ばせないか交渉'],
  Question.q77: ['はい', 'いいえ'],
  Question.q78: ['はい', 'いいえ'],
  Question.q79: ['はい', 'いいえ'],
  Question.q80: ['はい', 'いいえ'],
  Question.q81: ['文字', '絵・図形'],
  Question.q82: ['はい', 'いいえ'],
  Question.q83: ['イライラする', 'ワクワクする'],
  Question.q84: ['仲間と創るものだ', '自分の中にある'],
  Question.q85: ['はい', 'いいえ'],
  Question.q86: ['はい', 'いいえ'],
  Question.q87: ['はい', 'いいえ'],
  Question.q88: ['はい', 'いいえ'],
  Question.q89: ['はい', 'いいえ'],
  Question.q90: ['はい', 'いいえ'],
  Question.q91: ['はい', 'いいえ'],
  Question.q92: ['はい', 'いいえ'],
  Question.q93: ['はい', 'いいえ'],
  Question.q94: ['はい', 'いいえ'],
  Question.q95: ['はい', 'いいえ'],
  Question.q96: ['はい', 'いいえ'],
  Question.q97: ['笑ってから意味を尋ねる', '意味を尋ねてから笑う'],
  Question.q98: ['はい', 'いいえ'],
  Question.q99: ['はい', 'いいえ'],
  Question.q100: ['はい', 'いいえ'],
  Question.q101: ['はい', 'いいえ'],
  Question.q102: ['はい', 'いいえ'],
  Question.q103: ['はい', 'いいえ'],
  Question.q104: ['はい', 'いいえ'],
  Question.q105: ['はい', 'いいえ'],
  Question.q106: ['はい', 'いいえ'],
  Question.q107: ['はい', 'いいえ'],
  Question.q108: ['はい', 'いいえ'],
  Question.q109: ['はい', 'いいえ'],
  Question.q110: ['はい', 'いいえ'],
  Question.q111: ['「どんな感じがいい？」', '「まかせて！」'],
  Question.q112: ['はい', 'いいえ'],
  Question.q113: ['はい', 'いいえ'],
  Question.q114: ['はい', 'いいえ'],
  Question.q115: ['はい', 'いいえ'],
  Question.q116: ['はい', 'いいえ'],
  Question.q117: ['データを基にした主張', '思いつきの突飛なアイデア'],
  Question.q118: ['はい', 'いいえ'],
  Question.q119: ['はい', 'いいえ'],
  Question.q120: ['他人との向き合い方', '自分との向き合い方'],
  Question.q121: ['はい', 'いいえ'],
  Question.q122: ['資料を送る', 'スピーチをする'],
  Question.q123: ['はい', 'いいえ'],
  Question.q124: ['はい', 'いいえ'],
  Question.q125: ['はい', 'いいえ'],
  Question.q126: ['はい', 'いいえ'],
  Question.q127: ['はい', 'いいえ'],
  Question.q128: ['はい', 'いいえ'],
  Question.q129: ['はい', 'いいえ'],
  Question.q130: ['献立を決める', 'スーパーに向かう'],
  Question.q131: ['はい', 'いいえ'],
  Question.q132: ['はい', 'いいえ'],
  Question.q133: ['はい', 'いいえ'],
  Question.q134: ['はい', 'いいえ'],
  Question.q135: ['はい', 'いいえ'],
  Question.q136: ['はい', 'いいえ'],
  Question.q137: ['裸である理由', 'マニフェスト'],
  Question.q138: ['はい', 'いいえ'],
  Question.q139: ['はい', 'いいえ'],
  Question.q140: ['はい', 'いいえ'],
};

const Map<Question, int> questionClass = {
  Question.q1: 0,
  Question.q2: 160,
  Question.q3: 60,
  Question.q4: 30,
  Question.q5: 30,
  Question.q6: 170,
  Question.q7: 30,
  Question.q8: 70,
  Question.q9: 10,
  Question.q10: 140,
  Question.q11: 180,
  Question.q12: 40,
  Question.q13: 70,
  Question.q14: 20,
  Question.q15: 20,
  Question.q16: 20,
  Question.q17: 140,
  Question.q18: 180,
  Question.q19: 150,
  Question.q20: 70,
  Question.q21: 10,
  Question.q22: 50,
  Question.q23: 190,
  Question.q24: 20,
  Question.q25: 10,
  Question.q26: 70,
  Question.q27: 30,
  Question.q28: 120,
  Question.q29: 70,
  Question.q30: 40,
  Question.q31: 50,
  Question.q32: 50,
  Question.q33: 150,
  Question.q34: 170,
  Question.q35: 30,
  Question.q36: 70,
  Question.q37: 30,
  Question.q38: 180,
  Question.q39: 30,
  Question.q40: 10,
  Question.q41: 70,
  Question.q42: 120,
  Question.q43: 60,
  Question.q44: 110,
  Question.q45: 10,
  Question.q46: 20,
  Question.q47: 130,
  Question.q48: 190,
  Question.q49: 150,
  Question.q50: 160,
  Question.q51: 150,
  Question.q52: 10,
  Question.q53: 60,
  Question.q54: 190,
  Question.q55: 130,
  Question.q56: 50,
  Question.q57: 120,
  Question.q58: 110,
  Question.q59: 10,
  Question.q60: 130,
  Question.q61: 40,
  Question.q62: 130,
  Question.q63: 190,
  Question.q64: 120,
  Question.q65: 50,
  Question.q66: 40,
  Question.q67: 30,
  Question.q68: 50,
  Question.q69: 50,
  Question.q70: 40,
  Question.q71: 20,
  Question.q72: 50,
  Question.q73: 20,
  Question.q74: 50,
  Question.q75: 110,
  Question.q76: 40,
  Question.q77: 180,
  Question.q78: 60,
  Question.q79: 10,
  Question.q80: 30,
  Question.q81: 20,
  Question.q82: 140,
  Question.q83: 40,
  Question.q84: 10,
  Question.q85: 30,
  Question.q86: 160,
  Question.q87: 180,
  Question.q88: 20,
  Question.q89: 20,
  Question.q90: 190,
  Question.q91: 60,
  Question.q92: 40,
  Question.q93: 70,
  Question.q94: 10,
  Question.q95: 110,
  Question.q96: 60,
  Question.q97: 20,
  Question.q98: 60,
  Question.q99: 30,
  Question.q100: 40,
  Question.q101: 60,
  Question.q102: 30,
  Question.q103: 50,
  Question.q104: 160,
  Question.q105: 60,
  Question.q106: 40,
  Question.q107: 160,
  Question.q108: 170,
  Question.q109: 50,
  Question.q110: 50,
  Question.q111: 20,
  Question.q112: 40,
  Question.q113: 10,
  Question.q114: 30,
  Question.q115: 140,
  Question.q116: 70,
  Question.q117: 20,
  Question.q118: 30,
  Question.q119: 130,
  Question.q120: 10,
  Question.q121: 40,
  Question.q122: 40,
  Question.q123: 10,
  Question.q124: 10,
  Question.q125: 50,
  Question.q126: 150,
  Question.q127: 40,
  Question.q128: 120,
  Question.q129: 170,
  Question.q130: 40,
  Question.q131: 20,
  Question.q132: 50,
  Question.q133: 10,
  Question.q134: 30,
  Question.q135: 140,
  Question.q136: 70,
  Question.q137: 20,
  Question.q138: 170,
  Question.q139: 110,
  Question.q140: 0,
};
