import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:reegs/models/register/acquired_model.dart';

final EIProvider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final NSProvider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final FTProvider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final JPProvider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final HSPProvider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final PsyProvider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final SocProvider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

//Noの場合はここに入れる
final En0Provider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final En1Provider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final En2Provider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final En3Provider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final En4Provider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final En5Provider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final En6Provider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final En7Provider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final En8Provider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

final En9Provider = StateNotifierProvider<AcquiredController, List<int>>((ref) {
  return AcquiredController();
});

enum Question {
  q1,
  q2,
  q3,
  q4,
  q5,
  q6,
  q7,
  q8,
  q9,
  q10,
  q11,
  q12,
  q13,
  q14,
  q15,
  q16,
  q17,
  q18,
  q19,
  q20,
  q21,
  q22,
  q23,
  q24,
  q25,
  q26,
  q27,
  q28,
  q29,
  q30,
  q31,
  q32,
  q33,
  q34,
  q35,
  q36,
  q37,
  q38,
  q39,
  q40,
  q41,
  q42,
  q43,
  q44,
  q45,
  q46,
  q47,
  q48,
  q49,
  q50,
  q51,
  q52,
  q53,
  q54,
  q55,
  q56,
  q57,
  q58,
  q59,
  q60,
  q61,
  q62,
  q63,
  q64,
  q65,
  q66,
  q67,
  q68,
  q69,
  q70,
  q71,
  q72,
  q73,
  q74,
  q75,
  q76,
  q77,
  q78,
  q79,
  q80,
  q81,
  q82,
  q83,
  q84,
  q85,
  q86,
  q87,
  q88,
  q89,
  q90,
  q91,
  q92,
  q93,
  q94,
  q95,
  q96,
  q97,
  q98,
  q99,
  q100,
  q101,
  q102,
  q103,
  q104,
  q105,
  q106,
  q107,
  q108,
  q109,
  q110,
  q111,
  q112,
  q113,
  q114,
  q115,
  q116,
  q117,
  q118,
  q119,
  q120,
  q121,
  q122,
  q123,
  q124,
  q125,
  q126,
  q127,
  q128,
  q129,
  q130,
  q131,
  q132,
  q133,
  q134,
  q135,
  q136,
  q137,
  q138,
}

const Map<Question, String> questionTexts = {
  Question.q1: 'プライベートなことを人に質問されるのが好きだ',
  Question.q2: '衝動に駆られて行動を起こすことが多い',
  Question.q3: '口論になった際、相手を説き伏せられる自信がある',
  Question.q4: '大切な人が明らかに苦しそうな時、あなたが"先に"言いそうなのは…',
  Question.q5: 'あなたは人とすぐに打ち解けることができると思う',
  Question.q6: '他人の良いところより、欠点や短所などがどちらかというと目に付く',
  Question.q7: '失敗した時、まず自分以外に原因を探してしまう',
  Question.q8: '食事や飲み会は、同伴者が',
  Question.q9: '他人は自分ほど人生を深く味わっていないと思う',
  Question.q10: '他人から助けや同情を受けることは嫌いだ',
  Question.q11: '目的を定めて貯金をし、それを実現した経験がある',
  Question.q12: '信頼関係がある人を除いて、人を馬鹿にしてしまう事がある',
  Question.q13: 'あなたは面接官です。あなたがまず気になるのは…',
  Question.q14: '駅や街にいる全く知らない人について、特に感想を抱かない',
  Question.q15: '未来に何が起こるかより、今起きていることが大事だ',
  Question.q16: '他人の中に、自分にないものを見つけると羨ましく思う',
  Question.q17: '必要があれば人と対立することを恐れない',
  Question.q18: '問題が起きても、自分一人で考えて解決しようとする方だ',
  Question.q19: '普段から、自分の魅力を周りの人に分かって欲しいと思っている',
  Question.q20: '"意外と毒舌だよね"等と言われたことがある',
  Question.q21: '他人を良い気分にさせる方法をすぐに思いつく',
  Question.q22: '他の人から見て、あなたは落ち着いていると思う',
  Question.q23: '人類の進歩により必要なのは',
  Question.q24: '小さいころよくやっていたのは…',
  Question.q25: '自分の将来の仕事や生き方について、あまり興味がない',
  Question.q26: '自分がいまこうしていられるのは、基本的に自分のおかげである',
  Question.q27: '困っている人を見ると、手を差し伸べずにはいられない',
  Question.q28: '人が見ていない時に"ちょっと悪い事をしてしまおう"と魔が差すことがある',
  Question.q29: '時間にルーズな人間に腹を立てることがある',
  Question.q30: '環境の微妙な変化によく気づきやすい',
  Question.q31: '同時にたくさんのことを頼まれてもつい引き受けてしまう',
  Question.q32: '他人の行動や周囲の状況を一歩引いて見ることが多いと思う',
  Question.q33: '自分が欲しいものがあると、我慢できないでよくすぐに買ってしまう',
  Question.q34: 'チームとして正しい結論を出すためには、揉め事は避けて通れない',
  Question.q35: 'いつか自分が罪を犯すような気がする',
  Question.q36: 'あなたにとって、比較的重要性が高いのは…',
  Question.q37: '怒ると、あなたの言葉や行動は乱暴になることが多い',
  Question.q38: '打ち合わせ中に誰かが泣き出しました。まずあなたは…',
  Question.q39: 'SNSなどで日常を公開することに抵抗がない',
  Question.q40: '誰にも言えない様な秘密がある',
  Question.q41: '他人との感情のつながりはとても大切だと思う',
  Question.q42: '自分は優れていて特別な人だと思う',
  Question.q43: '不満なことは、はっきり伝えるほうだ',
  Question.q44: '他人と長く時間を過ごすことに疲労を感じやすい',
  Question.q45: 'チームの意見が割れました。リーダーのあなたはまず…',
  Question.q46: '会話の中で自分の自慢をすることがよくある',
  Question.q47: 'あなたは他の人よりも上に立つことや有名になることに興味がある',
  Question.q48: 'あなたは一般的なルールや習慣をすぐには受け入れる方だ',
  Question.q49: '仲間はずれにされたり、無視されたりするのはとても怖いと感じる',
  Question.q50: '一人でいる時間が十分に欲しいと思う',
  Question.q51: '面白そうだと思うのは…',
  Question.q52: '自分の利害に基づいて人を動かしたいと思う',
  Question.q53: '何もしないでリラックスしている時間が好きだ',
  Question.q54: '自分は人生で成功すると確信している',
  Question.q55: '色々な気持ちが一度に押し寄せて辛くなることがある',
  Question.q56: 'プレゼントをあげるのが好きで、人が喜ぶ顔を見るのを嬉しく思う',
  Question.q57: '楽しさより、正しさで行動を決める',
  Question.q58: 'チャットやメールなど、自分からやり取りをはじめる方だ',
  Question.q59: '自分は能力があり、社会に貢献できると信じている',
  Question.q60: 'あなたは海賊船の船長です。誘いたい船員は…',
  Question.q61: '人から良い反応を得るためには、第一印象がとても大切だ',
  Question.q62: '他の人から見て、あなたはのんびりしていると思う',
  Question.q63: '人に頼られすぎると負担に感じることがある',
  Question.q64: '誰もいない場所へ突然行きたくなることがある',
  Question.q65: '所持金や鑑賞した作品など、生活の記録を取る方だ',
  Question.q66: '初対面で愛想が悪いのも個性のひとつだと思う',
  Question.q67: '辛い状況が続くと、誰もいない場所に閉じこもりたくなる',
  Question.q68: '監視されていると本来の能力がほとんど発揮できない',
  Question.q69: '占いや手相などが当たっていて驚いたことがある',
  Question.q70: '暗号やパズルなどに挑戦することに苦痛を感じない',
  Question.q71: '同時に異なるタスクを強いられると、パニックに陥る',
  Question.q72: '死んだらどうなるかなど、考えるだけ無駄である',
  Question.q73: '気分が一定であることを重要視している',
  Question.q74: '自分には正直でいたいと感じる',
  Question.q75: '締切を提示されたら、あなたはまず…',
  Question.q76: '自分がやりたいことを我慢するのは嫌だ',
  Question.q77: 'ほしいものを手に入れるためには、どんな方法でも使う',
  Question.q78: '自分の周りの友人同士を引き合わせることがある',
  Question.q79: 'ルールに忠実な人は場合によって損をしていると思う',
  Question.q80: 'どうしてもタトゥーを入れるなら',
  Question.q81: '自分を平凡な人だとは思いたくない',
  Question.q82: '予想外の出来事が起きるとあなたは…',
  Question.q83: '素晴らしいアイデアは',
  Question.q84: 'たいていの人に理解してもらえない自分なりの意見を持っている',
  Question.q85: '一度決めたら最後までしっかりとやりとげる',
  Question.q86: '他人から少し冷たいとか、近づきにくいと言われたことがある',
  Question.q87: '一目で理解しにくいアイデアには関心を抱きにくい',
  Question.q88: '演奏や創作、ダンスなどの自己表現は自分に向いていない',
  Question.q89: '他人に何かを強制する、または他人から強制されると反抗的になることが多い',
  Question.q90: 'よく嘘をつく',
  Question.q91: '即座に気の利いた切り返しをするのが得意ではない',
  Question.q92: '約束事をすぐに破ってしまいやすい',
  Question.q93: '寝ることで悩みはいくらかマシになる',
  Question.q94: '自分でできることであれば、他人に頼れる場合でも自分でこなす',
  Question.q95: '口が達者だと言われることが多い',
  Question.q96: '恋人が言った冗談の意味が分かりませんでした。あなたはまず…',
  Question.q97: '目の前で誰かが泣いてても心が全く動かない',
  Question.q98: '結果を出しているものには逆らえないと思う',
  Question.q99: '多少完成度が低くても、締切は厳守したいと思う',
  Question.q100: '他人が自分のことをどう思うのかがとても気になる',
  Question.q101: '正論を言って場をシラけさせた経験がある',
  Question.q102: '新しい環境や出会いに抵抗がある',
  Question.q103: '新しい考えや初めてのことについては、不安を感じやすく慎重になる',
  Question.q104: '自分は何も悪いことをしていないのに、他の人からよく責められる',
  Question.q105: '100歳まで長生きする方法があるなら、苦しんででも実践したい',
  Question.q106: '起こってもいないことを心配することや取り越し苦労をすることがよくある',
  Question.q107: '頭の中で色々な楽しい計画を立てることがよくある',
  Question.q108: '何かしらの失敗をしないよう常に気を張っている気がする',
  Question.q109: '環境音や話し声に反応してしまいやすい',
  Question.q110: '「似顔絵描いて」と頼まれました。あなたが答えそうなのは…',
  Question.q111: '鍵や財布などを置く（しまう）場所が定まっている',
  Question.q112: '友人や恋人、家族に自分から電話をかけるほうだ',
  Question.q113: 'クラスや職場などの人間関係（誰と誰が親密かなど）を把握していない',
  Question.q114: '意識していないが、演技していると言われることがある',
  Question.q115: '人の目を見るのが苦手だ',
  Question.q116: 'あなたの関心が向きやすいのは…',
  Question.q117: '上司や先輩から「可愛がられる」ようなことがあまりない',
  Question.q118: '注目されるのが好きで、人前に出るのが好きだ',
  Question.q119: '悩みが多いのは…',
  Question.q120: 'ルーティンワークをこなしていくことがどちらかといえば得意だ',
  Question.q121: '長年温めていた計画を多くの人に発表します。あなたはまず…',
  Question.q122: '物事について深く考えすぎることはあまりない',
  Question.q123: '問題が起きると誰かに相談して意見を仰ぐ方だ',
  Question.q124: '人を傷つけるような描写や表現が苦手だ',
  Question.q125: 'すべてが公平で公正に行われているかどうかをとても気にする',
  Question.q126: 'なんとなくでも人生の設計があり、それに沿って進む気がある',
  Question.q127: '多くの人から好かれていると感じる',
  Question.q128: '冗談を言ったり、楽しい話をして人を楽しませるのが好きだ',
  Question.q129: '夜ごはんを作ることになりました。あなたはまず…',
  Question.q130: '何も考えず、ぼーっと景色や人々を眺めていられる',
  Question.q131: '他人の気分に影響を受けやすい',
  Question.q132: '初対面の人と話す話題はすぐ思いつく方だ',
  Question.q133: 'テレビやYoutubeを見ていて、退屈なCMや番組構成に文句を言ってしまうことがある',
  Question.q134: '空想の中で、ドラマの主役を演じることがある',
  Question.q135: '今まで人のことを、心の底から好きになったという経験がない',
  Question.q136: '駅前で裸の政治家が演説をしていました。あなたがまず気になるのは…',
  Question.q137: 'あなたは他人から見て、悩みが少なく幸せな人に見えると思う',
  Question.q138: '他人の悪事を見過ごすのが苦手だ'
};

const Map<Question, List<String>> questionAnswers = {
  Question.q1: ['はい', 'いいえ'],
  Question.q2: ['はい', 'いいえ'],
  Question.q3: ['はい', 'いいえ'],
  Question.q4: ['「どうしたの？」', '「大丈夫？」'],
  Question.q5: ['はい', 'いいえ'],
  Question.q6: ['はい', 'いいえ'],
  Question.q7: ['はい', 'いいえ'],
  Question.q8: ['多いほどいい', '少ないほどいい'],
  Question.q9: ['はい', 'いいえ'],
  Question.q10: ['はい', 'いいえ'],
  Question.q11: ['はい', 'いいえ'],
  Question.q12: ['はい', 'いいえ'],
  Question.q13: ['経歴', '話し方・態度'],
  Question.q14: ['はい', 'いいえ'],
  Question.q15: ['はい', 'いいえ'],
  Question.q16: ['はい', 'いいえ'],
  Question.q17: ['はい', 'いいえ'],
  Question.q18: ['はい', 'いいえ'],
  Question.q19: ['はい', 'いいえ'],
  Question.q20: ['はい', 'いいえ'],
  Question.q21: ['はい', 'いいえ'],
  Question.q22: ['はい', 'いいえ'],
  Question.q23: ['論文', '物語'],
  Question.q24: ['みんなでボール遊び', 'ひとりでゲーム'],
  Question.q25: ['はい', 'いいえ'],
  Question.q26: ['はい', 'いいえ'],
  Question.q27: ['はい', 'いいえ'],
  Question.q28: ['はい', 'いいえ'],
  Question.q29: ['はい', 'いいえ'],
  Question.q30: ['はい', 'いいえ'],
  Question.q31: ['はい', 'いいえ'],
  Question.q32: ['はい', 'いいえ'],
  Question.q33: ['はい', 'いいえ'],
  Question.q34: ['はい', 'いいえ'],
  Question.q35: ['はい', 'いいえ'],
  Question.q36: ['話し合いの時間', '話し合いの場所'],
  Question.q37: ['はい', 'いいえ'],
  Question.q38: ['迷惑に感じる', '心配に思う'],
  Question.q39: ['はい', 'いいえ'],
  Question.q40: ['はい', 'いいえ'],
  Question.q41: ['はい', 'いいえ'],
  Question.q42: ['はい', 'いいえ'],
  Question.q43: ['はい', 'いいえ'],
  Question.q44: ['はい', 'いいえ'],
  Question.q45: ['統計を取り総意を出す', '1人ずつに話を聞いてみる'],
  Question.q46: ['はい', 'いいえ'],
  Question.q47: ['はい', 'いいえ'],
  Question.q48: ['はい', 'いいえ'],
  Question.q49: ['はい', 'いいえ'],
  Question.q50: ['はい', 'いいえ'],
  Question.q51: ['著名な玄人の安定した漫才', '無名な若手の支離滅裂な一発芸'],
  Question.q52: ['はい', 'いいえ'],
  Question.q53: ['はい', 'いいえ'],
  Question.q54: ['はい', 'いいえ'],
  Question.q55: ['はい', 'いいえ'],
  Question.q56: ['はい', 'いいえ'],
  Question.q57: ['はい', 'いいえ'],
  Question.q58: ['はい', 'いいえ'],
  Question.q59: ['はい', 'いいえ'],
  Question.q60: ['目星を付けて誘う', '道中で見つけてゆく'],
  Question.q61: ['はい', 'いいえ'],
  Question.q62: ['はい', 'いいえ'],
  Question.q63: ['はい', 'いいえ'],
  Question.q64: ['はい', 'いいえ'],
  Question.q65: ['はい', 'いいえ'],
  Question.q66: ['はい', 'いいえ'],
  Question.q67: ['はい', 'いいえ'],
  Question.q68: ['はい', 'いいえ'],
  Question.q69: ['はい', 'いいえ'],
  Question.q70: ['はい', 'いいえ'],
  Question.q71: ['はい', 'いいえ'],
  Question.q72: ['はい', 'いいえ'],
  Question.q73: ['はい', 'いいえ'],
  Question.q74: ['はい', 'いいえ'],
  Question.q75: ['予定を立ててみる', '伸ばせないか交渉'],
  Question.q76: ['はい', 'いいえ'],
  Question.q77: ['はい', 'いいえ'],
  Question.q78: ['はい', 'いいえ'],
  Question.q79: ['はい', 'いいえ'],
  Question.q80: ['文字', '絵・図形'],
  Question.q81: ['はい', 'いいえ'],
  Question.q82: ['イライラする', 'ワクワクする'],
  Question.q83: ['仲間と創るものだ', '自分の中にある'],
  Question.q84: ['はい', 'いいえ'],
  Question.q85: ['はい', 'いいえ'],
  Question.q86: ['はい', 'いいえ'],
  Question.q87: ['はい', 'いいえ'],
  Question.q88: ['はい', 'いいえ'],
  Question.q89: ['はい', 'いいえ'],
  Question.q90: ['はい', 'いいえ'],
  Question.q91: ['はい', 'いいえ'],
  Question.q92: ['はい', 'いいえ'],
  Question.q93: ['はい', 'いいえ'],
  Question.q94: ['はい', 'いいえ'],
  Question.q95: ['はい', 'いいえ'],
  Question.q96: ['笑ってから意味を尋ねる', '意味を尋ねてから笑う'],
  Question.q97: ['はい', 'いいえ'],
  Question.q98: ['はい', 'いいえ'],
  Question.q99: ['はい', 'いいえ'],
  Question.q100: ['はい', 'いいえ'],
  Question.q101: ['はい', 'いいえ'],
  Question.q102: ['はい', 'いいえ'],
  Question.q103: ['はい', 'いいえ'],
  Question.q104: ['はい', 'いいえ'],
  Question.q105: ['はい', 'いいえ'],
  Question.q106: ['はい', 'いいえ'],
  Question.q107: ['はい', 'いいえ'],
  Question.q108: ['はい', 'いいえ'],
  Question.q109: ['はい', 'いいえ'],
  Question.q110: ['「どんな感じがいい？」', '「まかせて！」'],
  Question.q111: ['はい', 'いいえ'],
  Question.q112: ['はい', 'いいえ'],
  Question.q113: ['はい', 'いいえ'],
  Question.q114: ['はい', 'いいえ'],
  Question.q115: ['はい', 'いいえ'],
  Question.q116: ['データを基にした主張', '思いつきの突飛なアイデア'],
  Question.q117: ['はい', 'いいえ'],
  Question.q118: ['はい', 'いいえ'],
  Question.q119: ['他人との向き合い方', '自分との向き合い方'],
  Question.q120: ['はい', 'いいえ'],
  Question.q121: ['資料を送る', 'スピーチをする'],
  Question.q122: ['はい', 'いいえ'],
  Question.q123: ['はい', 'いいえ'],
  Question.q124: ['はい', 'いいえ'],
  Question.q125: ['はい', 'いいえ'],
  Question.q126: ['はい', 'いいえ'],
  Question.q127: ['はい', 'いいえ'],
  Question.q128: ['はい', 'いいえ'],
  Question.q129: ['献立を決める', 'スーパーに向かう'],
  Question.q130: ['はい', 'いいえ'],
  Question.q131: ['はい', 'いいえ'],
  Question.q132: ['はい', 'いいえ'],
  Question.q133: ['はい', 'いいえ'],
  Question.q134: ['はい', 'いいえ'],
  Question.q135: ['はい', 'いいえ'],
  Question.q136: ['裸である理由', 'マニフェスト'],
  Question.q137: ['はい', 'いいえ'],
  Question.q138: ['はい', 'いいえ'],
};

const Map<Question, int> questionClass = {
  Question.q1: 160,
  Question.q2: 60,
  Question.q3: 30,
  Question.q4: 30,
  Question.q5: 170,
  Question.q6: 30,
  Question.q7: 70,
  Question.q8: 10,
  Question.q9: 140,
  Question.q10: 180,
  Question.q11: 40,
  Question.q12: 70,
  Question.q13: 20,
  Question.q14: 20,
  Question.q15: 20,
  Question.q16: 140,
  Question.q17: 180,
  Question.q18: 150,
  Question.q19: 70,
  Question.q20: 10,
  Question.q21: 50,
  Question.q22: 190,
  Question.q23: 20,
  Question.q24: 10,
  Question.q25: 70,
  Question.q26: 30,
  Question.q27: 120,
  Question.q28: 70,
  Question.q29: 40,
  Question.q30: 50,
  Question.q31: 50,
  Question.q32: 150,
  Question.q33: 170,
  Question.q34: 30,
  Question.q35: 70,
  Question.q36: 30,
  Question.q37: 180,
  Question.q38: 30,
  Question.q39: 10,
  Question.q40: 70,
  Question.q41: 120,
  Question.q42: 60,
  Question.q43: 110,
  Question.q44: 10,
  Question.q45: 20,
  Question.q46: 130,
  Question.q47: 190,
  Question.q48: 150,
  Question.q49: 160,
  Question.q50: 150,
  Question.q51: 10,
  Question.q52: 60,
  Question.q53: 190,
  Question.q54: 130,
  Question.q55: 50,
  Question.q56: 120,
  Question.q57: 110,
  Question.q58: 10,
  Question.q59: 130,
  Question.q60: 40,
  Question.q61: 130,
  Question.q62: 190,
  Question.q63: 120,
  Question.q64: 50,
  Question.q65: 40,
  Question.q66: 30,
  Question.q67: 50,
  Question.q68: 50,
  Question.q69: 40,
  Question.q70: 20,
  Question.q71: 50,
  Question.q72: 20,
  Question.q73: 50,
  Question.q74: 110,
  Question.q75: 40,
  Question.q76: 180,
  Question.q77: 60,
  Question.q78: 10,
  Question.q79: 30,
  Question.q80: 20,
  Question.q81: 140,
  Question.q82: 40,
  Question.q83: 10,
  Question.q84: 30,
  Question.q85: 160,
  Question.q86: 180,
  Question.q87: 20,
  Question.q88: 20,
  Question.q89: 190,
  Question.q90: 60,
  Question.q91: 40,
  Question.q92: 70,
  Question.q93: 10,
  Question.q94: 110,
  Question.q95: 60,
  Question.q96: 20,
  Question.q97: 60,
  Question.q98: 30,
  Question.q99: 40,
  Question.q100: 60,
  Question.q101: 30,
  Question.q102: 50,
  Question.q103: 160,
  Question.q104: 60,
  Question.q105: 40,
  Question.q106: 160,
  Question.q107: 170,
  Question.q108: 50,
  Question.q109: 50,
  Question.q110: 20,
  Question.q111: 40,
  Question.q112: 10,
  Question.q113: 30,
  Question.q114: 140,
  Question.q115: 70,
  Question.q116: 20,
  Question.q117: 30,
  Question.q118: 130,
  Question.q119: 10,
  Question.q120: 40,
  Question.q121: 40,
  Question.q122: 10,
  Question.q123: 10,
  Question.q124: 50,
  Question.q125: 150,
  Question.q126: 40,
  Question.q127: 120,
  Question.q128: 170,
  Question.q129: 40,
  Question.q130: 20,
  Question.q131: 50,
  Question.q132: 10,
  Question.q133: 30,
  Question.q134: 140,
  Question.q135: 70,
  Question.q136: 20,
  Question.q137: 170,
  Question.q138: 110,
};
